import React, { useState, useEffect } from 'react';
import { api } from '../lib/api';
import { InsightsData } from '../types';

interface ReportData {
  priorities: Array<{
    title: string;
    description: string;
    impact: string;
  }>;
  risks: string[];
  generated_at: string;
}

export function WeeklyReport() {
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    setLoading(true);
    setError('');

    try {
      const response = await api.get('/weekly-report');
      setReport(response.data);
    } catch (err: any) {
      if (err?.response?.status === 404) {
        generateClientSideReport();
      } else {
        setError('Failed to fetch weekly report');
      }
    } finally {
      setLoading(false);
    }
  };

  const generateClientSideReport = () => {
    const storedData = localStorage.getItem('lastInsights');
    if (!storedData) {
      setError('No insights data available. Please upload and analyze data first.');
      return;
    }

    const insights: InsightsData = JSON.parse(storedData);
    const products = insights.insights?.products || insights.products || [];

    const highUrgency = products.filter(p => p.reorder?.urgency === 'high');
    const alerts = products.filter(p => p.anomalies && p.anomalies.length > 0);
    const lowConfidence = products.filter(p => p.confidence_score < 60);

    const priorities = [
      {
        title: 'High Priority Reorders',
        description: highUrgency.length > 0
          ? `${highUrgency.length} products need urgent reordering: ${highUrgency.slice(0, 3).map(p => p.product_name).join(', ')}`
          : 'No urgent reorders needed this week',
        impact: highUrgency.length > 0 ? 'Prevent stockouts and maintain sales' : 'Maintain current inventory levels'
      },
      {
        title: 'Demand Anomalies',
        description: alerts.length > 0
          ? `${alerts.length} products showing unusual patterns: ${alerts.slice(0, 3).map(p => p.product_name).join(', ')}`
          : 'All products showing normal demand patterns',
        impact: alerts.length > 0 ? 'Adjust inventory and pricing strategy' : 'Continue current operations'
      },
      {
        title: 'Review Low Confidence Items',
        description: lowConfidence.length > 0
          ? `${lowConfidence.length} products have low confidence scores and need manual review`
          : 'All forecasts have acceptable confidence levels',
        impact: lowConfidence.length > 0 ? 'Verify data quality and adjust forecasts' : 'Trust automated recommendations'
      }
    ];

    const risks = [];
    if (highUrgency.length > 5) risks.push('Multiple products at risk of stockout');
    if (alerts.length > 3) risks.push('Unusual demand patterns detected across multiple products');
    if (lowConfidence.length > products.length * 0.3) risks.push('Data quality issues affecting forecast accuracy');
    if (risks.length === 0) risks.push('No significant risks identified');

    setReport({
      priorities,
      risks,
      generated_at: new Date().toISOString()
    });
  };

  const copyToClipboard = () => {
    if (!report) return;

    const markdown = `# Weekly Business Report
Generated: ${new Date(report.generated_at).toLocaleDateString()}

## Top 3 Priorities

${report.priorities.map((p, i) => `### ${i + 1}. ${p.title}
${p.description}

**Expected Impact:** ${p.impact}
`).join('\n')}

## Risks & Alerts

${report.risks.map(r => `- ${r}`).join('\n')}

---
*Generated by Merchant Intelligence Copilot*
`;

    navigator.clipboard.writeText(markdown);
    alert('Report copied to clipboard as Markdown!');
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-xl p-12 text-center border border-gray-200 dark:border-gray-700">
          <div className="text-6xl mb-4">⏳</div>
          <p className="text-gray-600 dark:text-gray-400">Loading weekly report...</p>
        </div>
      </div>
    );
  }

  if (error && !report) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-xl p-12 text-center border border-gray-200 dark:border-gray-700">
          <div className="text-6xl mb-4">📋</div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">No Report Available</h2>
          <p className="text-gray-600 dark:text-gray-400">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Weekly Report</h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            AI-generated action plan for the week ahead
          </p>
        </div>
        <button
          onClick={copyToClipboard}
          className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-4 py-2 rounded-lg transition-colors"
        >
          Export
        </button>
      </div>

      {report && (
        <>
          <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">Top 3 Priorities</h2>
              <span className="text-sm text-gray-500 dark:text-gray-400">
                {new Date(report.generated_at).toLocaleDateString()}
              </span>
            </div>

            <div className="space-y-4">
              {report.priorities.map((priority, idx) => (
                <div key={idx} className="bg-gray-50 dark:bg-gray-700/50 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 w-8 h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center font-bold">
                      {idx + 1}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
                        {priority.title}
                      </h3>
                      <p className="text-gray-700 dark:text-gray-300 text-sm mb-2">
                        {priority.description}
                      </p>
                      <div className="bg-blue-50 dark:bg-blue-900/20 rounded px-3 py-2 border border-blue-200 dark:border-blue-800">
                        <p className="text-sm text-blue-800 dark:text-blue-200">
                          <strong>Expected Impact:</strong> {priority.impact}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Risks & Alerts</h2>
            <ul className="space-y-2">
              {report.risks.map((risk, idx) => (
                <li key={idx} className="flex items-start gap-3">
                  <span className="text-amber-500 mt-1">⚠️</span>
                  <span className="text-gray-700 dark:text-gray-300">{risk}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border border-blue-200 dark:border-blue-800">
            <p className="text-sm text-blue-800 dark:text-blue-200">
              💡 Automated insights. Review with your business knowledge.
            </p>
          </div>
        </>
      )}
    </div>
  );
}
